---
- hosts: localhost
  vars:
    sshcfg: '/etc/ansible/ssh.cfg'
    server: '10.0.0.141'
    src: '/srv/shareok/export/'
    dest: 'downloads/'
  tasks:
  - include: fetch.yml
- hosts: all
  vars:
    dspace_git: 'https://atmire.com/git/clients/oklahoma'
    dspace_src: '/vagrant/shareok_dspace'
    dspace_run: '/srv/shareok/dspace'
    dspace_env:
      MAVEN_PROFILE: 'vagrant'
      MAVEN: 'mvn'
      ANT: 'ant'
      TOMCAT: '/usr/share/tomcat'
      ANT_OPTS: '-Xms128m -Xmx800m'
      DB_HOST: 'localhost'
      DB_ADMIN: 'libacct'
      DB_ADMIN_PASS: 'libacct'
      DB_NAME: 'dspace'
      DB_PASS: 'dspace'
      DB_EXPORT: '/vagrant/downloads/shareokprod-20150922-dump.sql'
  sudo: yes
  environment: dspace_env
  tasks:
  - include: visudo.yml
  - include: shareok-prereqs.yml
  - include: shareok-build.yml
  - name: Ensure packages that work well with local VMs are installed.
    yum: name=chrony state=latest
