---
- hosts: localhost
  vars_files:
  - shareok-ec2-vars.yml
  tasks:
  - include: ec2-init-tasks.yml
#- hosts: 10.0.0.247
#  tasks:
#  - include: localsync.yml
#    vars:
#      src: '/srv/shareokdata/assetstore0/'
#      dest: '/srv/shareokdata/5x-assetstore0'
- hosts: unprovisioned
  vars_files:
  - shareok-ec2-vars.yml
  sudo: yes
  tasks:
  - include: base-server-tasks.yml
  - include: ec2-server-tasks.yml
  - include: shareok-prereqs.yml
  sudo: yes
  handlers:
  - include: base-server-handlers.yml
